"""Add image_filename to Product

Revision ID: 070c9a189886
Revises: 69ffc5fd8874
Create Date: 2025-09-13 16:52:34.370484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070c9a189886'
down_revision = '69ffc5fd8874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
