"""Add category to Product

Revision ID: 276c47c978c6
Revises: fae437438a99
Create Date: 2025-09-07 13:51:05.028333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276c47c978c6'
down_revision = 'fae437438a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
